### ISSUE TITLE
About the dataset using in Detection-of-Malicious-PDF-Files

### ISSUE THREAD

**Issue by snRNA** [fettay/DeePDF#1]
I am a graduate frofhina，majoring in malicious document detection. I learn about the paper "DETECTING MALICIOUS PDF USING CNN" from your GitHub. I gained a lot of interest. I wonder if I can get the document dataset you used in the paper. I would be grateful if you can agree. I will guarantee that I will only use these data sets for personal learning and research, and will not spread to others and other malicious uses. You could transfer the data using google drive, one drive, and other ways.
Thanks.
You could contact me from the email:
base64.b64decode("c24yMDE0MTExMjMwMTVAZ21haWwuY29t")

**Comment by fettay** [comment]
I can provide the malicious files

**Comment by snRNA** [comment]
I am happy to see your reply . And I can't wait to do some research
with the dataset. Thanks for your selfless dedication

2019-11-04 20:30 GMT+08:00, fettay <notifications@github.com>:
